[package]
name = "aoc-intervals"
version = "1.0.0"
edition = "2024"

[dependencies]
num-integer.workspace = true
num-traits.workspace = true
assertables.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
