[package]
name = "aoc-2022-05"
version = "1.0.0"
edition = "2024"

[dependencies]
include_dir.workspace = true
aoc-utils = { path = "../../../crates/aoc-utils" }

[dev-dependencies]
pretty_assertions.workspace = true
assertables.workspace = true
