[package]
name = "aoc-geometry"
version = "1.0.0"
edition = "2024"

[dependencies]
num-traits.workspace = true
num-integer.workspace = true
ndarray.workspace = true
itertools.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
assertables.workspace = true
